### ISSUE TITLE
iOS version is slow and crashes

### ISSUE THREAD

**Issue by mddrill** [drhelius/Gearboy#78] opened 2018-05-18 01:19 UTC
I posted about this in another issue, but I figured it should be an issue of it's own.

The iOS version of the emulator (I haven't tried any other version). Starts off very slow and after maybe 3 15 minute sessions of playing it, starts to crash upon opening it.

This is the error I get in the logs when it crashes.
 
> Failed to start job with error <NSError: 0x10078bc50; domain: NSPOSIXErrorDomain; code: 3; reason: "No such process"> {
> description = "Unable to get pid for label UIKitApplication:com.matthewdrill.Gearboy[0xb5d8][66]";
> failureReason = "No such process";
> userInfo = {
> BKLaunchdJobLabel = UIKitApplication:com.matthewdrill.Gearboy[0xb5d8][66];
> BKLaunchdOperation = launch_get_running_pid_4SB;
> }
> }

This basically means the iOS version is entirely unusable.

I'm happy to look into fixing this, but could use any guidance you could give me. I've never worked on an app where I had to worry about memory management like this (I'm assuming it's a memory management issue, idk what else it could be). I've looked at the memory allocation with the xcode instruments tool, and can see that between the resources allocated in the Memory::Init() function and the Cartridge::LoadFromBuffer() function, 3MB of memory is being allocated. I have no idea if that's a lot, or is part of the issue.

Have you tried looking into this problem before? Any ideas where I could start?

**Comment by drhelius** [comment] 2018-06-19 21:33
Is this still happening to you?

I can't reproduce it. I tested it on several hardware devices and everything is smooth and normal.

Does this happen with the same rom?

**Comment by mddrill** [comment] 2018-06-20 19:10
It was still happening last month (the last time I tried to use this).

Yes it was a specific ROM (Pokémon yellow) that I was using, but that ROM
worked fine on SameBoy.

I was using an iPhone 7.

**Comment by drhelius** [comment] 2018-06-21 22:38
Just tested that rom for several hours on iPad 5th gen and iPhone 8 and it plays nice.

I will be closing this issue for now. Feel free to open it agin if you happen to get crashes or slowdowns again.

In the meantime be sure to install the emulator by “profiling” it. This will compile and install it in your device with all the optimizations enabled.

**Closed by drhelius** 2018-06-21 22:38 UTC
